#index:
#    path: /
#    controller: App\Controller\DefaultController::index
welcome:
  path: /
  controller: App\Controller\WelcomeController::welcome

leadDetail:
  path: /details
  controller: App\Controller\InfoController::details
